"""Real-data-matched prior (todo section 30 / docs/real_prior_plan.md, 2026-09-03).

One prior whose per-table hyperparameters are BOOTSTRAPPED from the real-data census
(eval/results_realdata_shapes.json: OpenML-CC18 + Grinsztajn + TabArena, 156 datasets): a census
row is drawn per batch and its (feature count D, categorical fraction, category counts, intrinsic
dimension ratio K90/D) are used jointly, so the correlations between axes are kept. The table-level
noise sigma is bootstrapped from the census's regression noise (1 - R^2 of HistGB, as an equivalent
sigma under x = f + sigma * eps, Var f = 1). Rows are NOT matched: every real dataset exceeds the
1024-row cap, so the prior's R models the CONTEXT SIZE (log-uniform up to the cap), which is what
the model sees at inference.

Structure (the K axis): K = round(rho * D) latent ROOT nodes come first in topological order; each
observed column takes a random subset of the latents as parents (with prob p_latent_parent) plus
earlier observed columns with the SCM prior's edge_prob, and is generated by the SCM prior's own
mechanism families (MLP / TREE / DISC), standardised, then noised with a per-node sigma around the
table sigma. rho = K / D is sampled as the census's K90/D, i.e. as a RATIO (a ratio keeps rho
independent of D by construction; an absolute K would make the K axis a proxy of D). rho is the
generative side and K90/D the observed side; eval/real_prior_check.py measures the mapping.

Evaluation truth per table lives in SCMBatch.hyper (rho, K, D, R, sigma_table, ...), and the usual
f / adjacency / sigma / family arrays. Training reads only x.
"""
import json
from dataclasses import dataclass
from pathlib import Path

import numpy as np

from prior.scm import _NOISE, FuncFamily, PriorConfig, SCMBatch, _make_mechanism

ROOT = Path(__file__).parents[1]


@dataclass(frozen=True)
class RealConfig:
    census: str = "eval/results_realdata_shapes.json"
    n_rows: tuple = (16, 1024)          # context-size range, log-uniform per batch
    max_cells: int = 32768              # TabPFN v2's rule (75,000 cells there): a wide table gets fewer rows,
                                        # R = min(R, max_cells // D), so memory is bounded by D x R not by max D.
                                        # 32,768 = 32 cols x 1024 rows, the batch-4 peak measured on 48 GB (26 / 33 GB)
    max_cols: int = 64                  # census D capped here (p85 of the suite)
    force_cols: int = None              # smokes only: fix the feature count (worst case = max_cols; feature
                                        # attention is O(D^2) per row, so D=65 x R=504 outweighs D=32 x R=1024)
    max_categories: int = 16            # census category counts capped (ID-like columns excluded)
    sigma_cap: float = 3.0              # census sigma_equiv capped (one 31.6 outlier)
    sigma_scale: float = 0.1            # multiplier on the bootstrapped table sigma; CALIBRATED by
                                        # eval/real_prior_check.py so the HistGB noise fraction matches (the
                                        # census sigma is a target-column quantity; most of a real table's
                                        # columns are far more redundant than that)
    sigma_jitter: float = 0.3           # log-space jitter on the bootstrapped table sigma
    node_sigma_spread: tuple = (0.5, 2.0)   # per-node multiplier around the table sigma, log-uniform
    p_latent_parent: float = 0.9        # an observed column takes latent parents with this prob (if K > 0)
    latent_all: bool = False            # True: every such column sees ALL K latents (dense factor loadings; HistGB
                                        # cannot recover a dense combination from sibling columns, noise fraction
                                        # stays ~.26). False (default): SPARSE loadings, U[1, max_latent_parents]
                                        # latents per column, assigned by cycling a random order so every latent
                                        # is used before any repeats (keeps K90 ~ K while columns stay redundant)
    max_latent_parents: int = 2
    p_child_pure: float = 0.0           # a column with observed parents drops its latent parents with this prob.
                                        # Tried at 0.5 (2026-09-03): pure children duplicate their parents, which
                                        # LOWERED K90/D and over-predicted outcomes; kept at 0
    rho_gain: float = 1.0               # scalar fallback when rho_map is None
    rho_map: tuple = None               # None = identity (rho_gain 1.0). Once the check measures FEATURES only (target
                                        # excluded, like the census) the rho -> K90/D map is ~identity (600 tables,
                                        # 2026-09-03: .26->.27, .55->.54, .73->.67, .85->.85, 1.0->1.0), so no
                                        # pre-compensation; the field stays for re-calibration if the generator changes
                                        # inverse calibration: ((measured_k90d, rho_gen), ...) from
                                        # eval/results_real_prior_check.json's calibration table; the census K90/D is
                                        # mapped through it so the MEASURED K90/D of generated tables lands on the
                                        # real distribution (the rho -> K90/D map is sublinear: sparse loadings,
                                        # observed edges and nonlinear families all lower the measured ratio)
    edge_prob: tuple = (0.05, 0.25)     # observed -> observed edges (lower than the SCM prior's (0.15, 0.5):
                                        # child columns duplicate their parents' information and pull K90/D
                                        # below the real distribution)
    edge_scale_by_rho: bool = True      # p_edge *= (1 - rho): rho is "how much the columns share"; at rho -> 1 the
                                        # real tables are nearly independent columns (K90/D ~ .97), which observed
                                        # edges would otherwise cap at ~.75
    max_parents: int = 3                # cap on OBSERVED parents (latent parents are a separate subset)
    p_family: tuple = (0.9, 0.034, 0.033, 0.033)  # LINEAR, MLP, TREE, DISC for observed columns. The linear share is
                                        # CALIBRATED by eval/real_prior_check.py: it sets how redundant the
                                        # columns are (HistGB noise fraction) and how low-rank the table is (K90/D)
    target_sigma_scale: float = 0.8     # the target's noise = target_sigma_scale x the census sigma (no jitter),
                                        # CALIBRATED so the check's HistGB noise fraction matches the census (HistGB's
                                        # own fit error adds a few points, so the sigma is slightly under 1.0)
    target_classes: tuple = None        # classification prior: pool of class counts K; the designated target is discretised
                                        # into K classes (random quantile cuts, imbalanced like real labels); None = regression
    designate_target: bool = True       # the last observed column is a benchmark-style TARGET: a function of 1-3
                                        # earlier observed columns (no latent parents) with the census sigma as its
                                        # noise; it and its parents are never categorised (a regression target). The census noise fraction was measured on designated targets, so
                                        # the check measures this column; hyper["target_col"] locates it after
                                        # the column shuffle. One column per table: K90/D is unaffected.
    p_missing_table: float = 0.3
    missing_rate: tuple = (0.0, 0.1)


class RealPrior:
    def __init__(self, config: RealConfig = RealConfig(), seed: int = 0):
        self.config = config
        self.rng = np.random.default_rng(seed)
        rows = json.loads((ROOT / config.census).read_text())["rows"]
        self.rows = rows                                             # all 156 (the ~all-categorical 14 lack k90)
        self.rho_pool = np.array([r["k90_over_d"] for r in rows if "k90_over_d" in r])
        # per-COLUMN category counts pooled over all datasets: the census deciles are per column, and a
        # per-row pool would under-weight the wide binary-heavy datasets once D is capped
        self.ncat_pool = np.array([min(n, config.max_categories) for r in rows for n in r["cat_n_categories"] if n >= 2])
        self.sigmas = np.array([min(r["sigma_equiv"], config.sigma_cap) for r in rows if "sigma_equiv" in r])
        self._scm = PriorConfig(edge_prob=config.edge_prob, max_parents=config.max_parents)

    def _draw_table_params(self):
        c, rng = self.config, self.rng
        row = self.rows[int(rng.integers(len(self.rows)))]
        cat_frac = row["n_categorical"] / max(row["n_features"], 1)
        has_target = c.designate_target and (cat_frac < 0.9 or bool(c.target_classes))   # an ~all-categorical table has no continuous
                                                                                   # target; the classification prior labels every table
        D = int(min(row["n_features"], c.max_cols)) + (1 if has_target else 0)   # census D excludes the target column
        if c.force_cols:
            D = int(c.force_cols) + (1 if has_target else 0)
        rho_census = float(row["k90_over_d"]) if "k90_over_d" in row else float(self.rng.choice(self.rho_pool))
        if c.rho_map:
            xs, ys = zip(*c.rho_map)
            rho = float(np.interp(rho_census, xs, ys))
        else:
            rho = float(min(1.0, c.rho_gain * rho_census))
        K = int(round(rho * D))
        return D, K, rho, rho_census, cat_frac, self.ncat_pool, row["name"], has_target

    def sample_batch(self, batch_size: int) -> SCMBatch:
        c, rng = self.config, self.rng
        D, K, rho, rho_census, cat_frac, n_cat_pool, src, has_target = self._draw_table_params()   # per batch: shapes shared
        R = int(np.exp(rng.uniform(np.log(c.n_rows[0]), np.log(c.n_rows[1]))))
        R = min(R, max(c.max_cells // D, 10))                                          # cell budget (v2 rule); 10 = make_batch floor
        N = D + K
        x = np.empty((batch_size, R, D), np.float32)
        f = np.empty((batch_size, R, D), np.float32)
        adjacency = np.zeros((batch_size, N, N), bool)
        observed_idx = np.empty((batch_size, D), np.int16)
        func_family = np.zeros((batch_size, N), np.int8)
        noise_sigma = np.zeros((batch_size, N), np.float32)
        categorical = np.zeros((batch_size, D), np.int8)
        hyper = []
        for b in range(batch_size):
            sig_census = float(self.sigmas[int(rng.integers(len(self.sigmas)))])
            sig_t = float(c.sigma_scale * sig_census * np.exp(rng.uniform(-c.sigma_jitter, c.sigma_jitter)))
            xb, fb, adj, fam, sig, n_lat, tparents = self._sample_table(R, D, K, sig_t, rho, sig_census, has_target)
            obs = np.arange(K, N)
            rng.shuffle(obs)                                   # column order leaks no topology
            target_col = int(np.flatnonzero(obs == N - 1)[0]) if (has_target and D >= 2) else None
            x[b], f[b] = xb[:, obs], fb[:, obs]
            adjacency[b], func_family[b], noise_sigma[b] = adj, fam, sig
            observed_idx[b] = obs
            protect = np.isin(obs, tparents) | ((obs == N - 1) if has_target else False)   # target + parents stay continuous
            n_feat = D - (1 if has_target else 0)              # cat_frac is a fraction of the census FEATURES
            categorical[b] = self._postprocess(x[b], cat_frac * n_feat / D, n_cat_pool, protect)
            n_classes = 0
            if c.target_classes and target_col is not None:        # classification prior: K-class label column
                n_classes = int(c.target_classes[int(rng.integers(len(c.target_classes)))])
                col = x[b][:, target_col]
                edges = np.quantile(col[~np.isnan(col)], np.sort(rng.uniform(0.05, 0.95, size=n_classes - 1)))
                codes_perm = rng.permutation(n_classes)
                codes = codes_perm[np.digitize(np.nan_to_num(col), edges)]   # nominal ids: no code order to learn (TabPFN v2 labels are prototype indices)
                x[b][:, target_col] = np.where(np.isnan(col), np.nan, codes)
                categorical[b][target_col] = n_classes
            obs_edges = adj[K:, K:].sum()
            # C4: the label column's continuous truth (f) is still scoreable through the cut it was made with:
            # class(v) = class_perm[digitize(v, class_edges)]; without these the id column has no truth at all
            hyper.append({"rho": rho, "rho_census": rho_census, "K": K, "D": D, "R": R, "sigma_table": round(sig_t, 4), "n_classes": n_classes,
                          "class_edges": [float(e) for e in edges] if n_classes else None,
                          "class_perm": [int(k) for k in codes_perm] if n_classes else None,
                          "target_col": target_col, "target_sigma": round(getattr(self, "_last_target_sigma", float("nan")), 4) if target_col is not None else None,
                          "sigma_mean": round(float(sig[K:].mean()), 4), "cat_frac": round(float((categorical[b] > 0).mean()), 4),
                          "edge_density_obs": round(float(obs_edges / max(D * (D - 1) / 2, 1)), 4),
                          "latent_parents_mean": round(float(n_lat.mean()), 3), "source": src})
        return SCMBatch(x, f, adjacency, observed_idx, func_family, noise_sigma, categorical, hyper)

    def _sample_table(self, R, D, K, sig_t, rho, sig_census, has_target=True):
        c, rng = self.config, self.rng
        N = K + D
        xn = np.empty((R, N)); fn = np.empty((R, N))
        fam = np.zeros(N, np.int8); sig = np.zeros(N, np.float32)
        adj = np.zeros((N, N), bool)
        n_lat = np.zeros(D, int)
        tparents = np.array([], int)
        for k in range(K):                                     # latent roots: f := x, exogenous
            xn[:, k] = fn[:, k] = _NOISE[rng.choice(list(_NOISE))](rng, R)
        p_edge = rng.uniform(*c.edge_prob) * ((1 - rho) if c.edge_scale_by_rho else 1.0)
        order, pos = rng.permutation(K), 0                    # cycling assignment: coverage of all latents
        for i in range(D):
            j = K + i
            lat = np.array([], int)
            is_target = has_target and i == D - 1 and D >= 2
            if is_target:
                obs = np.sort(rng.choice(np.arange(K, j), min(int(rng.integers(1, 4)), i), replace=False))
                parents = tparents = obs
                adj[parents, j] = True
                family = FuncFamily(int(rng.choice([4, 1, 2, 3], p=c.p_family)))
                fam[j] = family
                for _ in range(3):
                    if family == FuncFamily.LINEAR:
                        raw = xn[:, parents] @ rng.normal(0, 1 / np.sqrt(len(parents)), len(parents))
                    else:
                        raw = _make_mechanism(rng, family, len(parents), self._scm)(xn[:, parents])
                    if raw.std() > 1e-6:
                        break
                std = raw.std()
                fj = (raw - raw.mean()) / (std + 1e-8) if std > 1e-8 else raw - raw.mean()
                s_t = float(np.clip(c.target_sigma_scale * sig_census, 0.01, 4.0))   # census sigma, no jitter
                sig[j] = s_t
                self._last_target_sigma = s_t
                fn[:, j] = fj
                xn[:, j] = fj + s_t * _NOISE[rng.choice(list(_NOISE))](rng, R)
                continue
            if K and rng.random() < c.p_latent_parent:
                if c.latent_all:
                    lat = np.arange(K)
                else:
                    # one latent w.p. rho (an almost-independent column), else up to max_latent_parents:
                    # this is what lets K90/D reach the real p90 (~.97 = nearly independent columns)
                    m = 1 if (K == 1 or rng.random() < rho) else int(rng.integers(2, min(K, c.max_latent_parents) + 1))
                    lat = np.sort(np.array([order[(pos + t) % K] for t in range(m)]))
                    pos = (pos + m) % K
                    if pos < m:                                # wrapped: reshuffle for the next cycle
                        order = rng.permutation(K)
            obs = np.flatnonzero(rng.random(i) < p_edge) + K if i else np.array([], int)
            if len(obs) > c.max_parents:
                obs = np.sort(rng.choice(obs, c.max_parents, replace=False))
            if len(obs) and len(lat) and rng.random() < c.p_child_pure:
                lat = np.array([], int)
            parents = np.concatenate([lat, obs]).astype(int)
            if len(parents) == 0:                              # orphan: exogenous like an SCM root
                dist = rng.choice(list(_NOISE))
                xn[:, j] = fn[:, j] = _NOISE[dist](rng, R)
                continue
            adj[parents, j] = True
            n_lat[i] = len(lat)
            family = FuncFamily(int(rng.choice([4, 1, 2, 3], p=c.p_family)))
            fam[j] = family
            for _ in range(3):
                if family == FuncFamily.LINEAR:
                    w = rng.normal(0, 1 / np.sqrt(len(parents)), len(parents))
                    raw = xn[:, parents] @ w
                else:
                    raw = _make_mechanism(rng, family, len(parents), self._scm)(xn[:, parents])
                if raw.std() > 1e-6:
                    break
            std = raw.std()
            fj = (raw - raw.mean()) / (std + 1e-8) if std > 1e-8 else raw - raw.mean()
            s = float(np.clip(sig_t * np.exp(rng.uniform(np.log(c.node_sigma_spread[0]), np.log(c.node_sigma_spread[1]))), 0.01, 4.0))
            sig[j] = s
            fn[:, j] = fj
            xn[:, j] = fj + s * _NOISE[rng.choice(list(_NOISE))](rng, R)
        return xn, fn, adj, fam, sig, n_lat, tparents

    def _postprocess(self, xb, cat_frac, n_cat_pool, protect=None):
        c, rng = self.config, self.rng
        R, D = xb.shape
        cat = np.zeros(D, np.int8)
        n_c = int(round(cat_frac * D))
        pool = np.flatnonzero(~protect) if protect is not None else np.arange(D)
        n_c = min(n_c, len(pool))
        for d in rng.choice(pool, n_c, replace=False) if n_c else []:
            k = int(n_cat_pool[int(rng.integers(len(n_cat_pool)))])
            edges = np.quantile(xb[:, d], np.sort(rng.uniform(size=k - 1)))
            xb[:, d] = np.digitize(xb[:, d], edges)
            cat[d] = k
        if rng.random() < c.p_missing_table:
            rate = rng.uniform(*c.missing_rate)
            xb[rng.random((R, D)) < rate] = np.nan
        return cat
