"""Generate the real-prior training configs deterministically (docs/real_prior_plan.md section 10).

Base recipe (configs/base_{ds,dual}_s0.yaml) + prior_source real + batch 4 (cell budget 32,768 cells/table
bounds memory at the batch-4 peak measured 2026-09-03: ds 26 GB / dual 33 GB on 48 GB) + lr grid scaled
from the base ratio (1e-3 @ batch 8 -> 5e-4 @ batch 4) + seeds. Re-run to regenerate; never hand-edit.

Run: python3 scripts/gen_real_configs.py            -> configs/real_{ds,dual}_lr{5e-4,1.7e-4,5e-5}_s{0,1,2}.yaml (+ edge lr 1.5e-3 / 1.7e-5 seed 0, +2 smokes; flat: remote.sh run routes on configs/<name>.yaml)
"""
from pathlib import Path

import yaml

ROOT = Path(__file__).parents[1]
LRS = {"5e-4": 5e-4, "1.7e-4": 1.7e-4, "5e-5": 5e-5}     # ratio, ratio/3, ratio/10 at batch 4
EDGE_LRS = {"1.5e-3": 1.5e-3, "1.7e-5": 1.7e-5}          # grid-edge rule (10.2): x3 above / /3 below, seed 0 only
CLS_CENSUS = ROOT / "eval/results_class_count_census.json"   # classification variant (2026-09-04): K pool = real suite class counts
SEEDS = (0, 1, 2)
STEPS = 20000

HEADER = ("# GENERATED by scripts/gen_real_configs.py (docs/real_prior_plan.md section 10). Do not hand-edit.\n"
          "# base recipe + prior_source real (prior/real.py defaults: census bootstrap, cell budget 32768) + batch 4.\n")


def main():
    out = ROOT / "configs"
    n = 0
    for arm in ("ds", "dual"):
        base = yaml.safe_load((ROOT / f"configs/base_{arm}_s0.yaml").read_text())
        for tag, lr in LRS.items():
            for seed in SEEDS:
                c = dict(base)
                c.update(run_name=f"real_{arm}_lr{tag}_s{seed}", seed=seed, steps=STEPS, batch_size=4, lr=lr,
                         prior_source="real", prior={})
                (out / f"{c['run_name']}.yaml").write_text(HEADER + yaml.safe_dump(c, sort_keys=False))
                n += 1
        for tag, lr in EDGE_LRS.items():
            c = dict(base)
            c.update(run_name=f"real_{arm}_lr{tag}_s0", seed=0, steps=STEPS, batch_size=4, lr=lr, prior_source="real", prior={})
            (out / f"{c['run_name']}.yaml").write_text(HEADER + yaml.safe_dump(c, sort_keys=False))
            n += 1
        c = dict(base)
        c.update(run_name=f"real_{arm}_smoke", seed=0, steps=40, batch_size=4, lr=5e-4, prior_source="real",
                 prior={"n_rows": [1024, 1024], "force_cols": 64})   # worst case D=65 (feature attention O(D^2)); the
                                                                     # cell budget then sets R = 32768 // 65 = 504
        (out / f"{c['run_name']}.yaml").write_text(HEADER + yaml.safe_dump(c, sort_keys=False))
        n += 1
    # classification-only variant: policy y_target, class head n_classes=10, prior target discretised with K drawn from
    # the real suite's class-count census (bootstrap of the observed n_classes list, capped at 10).
    import json
    pool = sorted(min(int(r["n_classes"]), 10) for r in json.loads(CLS_CENSUS.read_text())["datasets"] if r.get("n_classes"))
    for arm in ("ds", "dual"):
        base = yaml.safe_load((ROOT / f"configs/base_{arm}_s0.yaml").read_text())
        # pre-registered arms at lr 5e-4 x 3 seeds (11); lr 1.7e-4 seed 0 = lr control added 2026-09-04 after the live
        # cls_ds_s0 val NLL rose monotonically from step 750 (not pre-registered; reported as a control, never as an arm)
        # 11.2 lr re-match (2026-09-04 13:58): the 1.7e-4 control beat every 5e-4 ds seed by step 3250 -> grid rule of 10.2 for the
        # class-head arms: 5e-5 seed 0 (makes 1.7e-4 interior) + 1.7e-4 seeds 1-2. Reported as 11.2, never mixed into the 11 arms.
        for tag, lr, seed in [("5e-4", 5e-4, s) for s in SEEDS] + [("1.7e-4", 1.7e-4, s) for s in SEEDS] + [("5e-5", 5e-5, 0)]:
            c = dict(base)
            c.update(run_name=f"cls_{arm}_lr{tag}_s{seed}", seed=seed, steps=STEPS, batch_size=4, lr=lr, prior_source="real",
                     prior={"target_classes": pool}, n_classes=10)
            c["policy" if arm == "ds" else "policy_main"] = "y_target"
            (out / f"{c['run_name']}.yaml").write_text(HEADER + yaml.safe_dump(c, sort_keys=False))
            n += 1
        c = dict(base)
        c.update(run_name=f"cls_{arm}_smoke", seed=0, steps=40, batch_size=4, lr=5e-4, prior_source="real",
                 prior={"target_classes": pool, "n_rows": [1024, 1024], "force_cols": 64}, n_classes=10)
        c["policy" if arm == "ds" else "policy_main"] = "y_target"
        (out / f"{c['run_name']}.yaml").write_text(HEADER + yaml.safe_dump(c, sort_keys=False))
        n += 1
    print(f"wrote {n} configs to configs/real_*.yaml + configs/cls_*.yaml (class pool n={len(pool)}, K in {min(pool)}..{max(pool)})")


if __name__ == "__main__":
    main()
