"""Generate the paper_v4 training configs from the pre-registration (paper_v4/experiments.yaml), deterministically.

Name rule (paper_v4/docs/04 section 2): v4_{arm}_{mech}_lam{lambda}_lr{lr}_{policy}_{target}_s{seed}[.yaml]; E5 adds a
_{steps}k slot before the seed. Base recipe = configs/base_{ds,dual}_s0.yaml + prior_source real + batch 4 + 20k steps,
exactly as scripts/gen_real_configs.py built the POST runs (so reuse_existing runs ARE cells of the grid; the generator
verifies that against their configs and refuses otherwise). C9: the E1b arm is mode sigreg, lambda_sig from the spec.

E2 / E5 (and E4, which also needs C8) hang on "E1 best": pass --e1-best lam=<l>,lr=<lr> or let the generator read
eval/results_v4_e1_collapse_grid.json["best_cell"] once E1 is in; E6 hangs on "best_cell_lat" (--e1-best-lat) the same way;
until then they are listed as pending.

Run: python3 scripts/gen_v4_configs.py [--e1-best lam=0.1,lr=5e-4]   -> configs/v4_*.yaml + configs/v4_manifest.json
"""
import json
import re
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).parents[1]
SPEC = ROOT / "paper_v4/experiments.yaml"
MANIFEST = ROOT / "configs/v4_manifest.json"
E1_ARTIFACT = ROOT / "eval/results_v4_e1_collapse_grid.json"
STEPS, BATCH = 20000, 4
HEADER = "# GENERATED by scripts/gen_v4_configs.py from paper_v4/experiments.yaml. Do not hand-edit.\n"


def lam_tag(l):
    return f"{l:g}"


def name(arm, mech, lam, lr, policy, target, seed, extra=None):
    return "_".join(["v4", arm, mech, f"lam{lam_tag(lam)}", f"lr{lr}", policy, target] + ([extra] if extra else []) + [f"s{seed}"])


def base(arm):
    c = yaml.safe_load((ROOT / f"configs/base_{arm}_s0.yaml").read_text())
    c.update(steps=STEPS, batch_size=BATCH, prior_source="real", prior={})
    return c


def cell(arm, mech, lam, lr, policy, target, seed, steps=STEPS, lambda_sig=None, drop_masked=None, extra=None, init_from=None, freeze=False, save_at=None, reinit_head=False):
    """One run = one config dict + its axis record. init_from / freeze = E6 two-stage (ds trainer, C14)."""
    c = base(arm)
    c.update(seed=seed, lr=float(lr), steps=steps, run_name=name(arm, mech, lam, lr, policy, target, seed, extra))
    if arm == "ds":
        c["policy"] = policy
        if init_from:
            c.update(init_from=init_from, freeze_encoder=bool(freeze))
            if reinit_head:
                c["reinit_head"] = True
    else:
        c.update(policy_main=policy, mode=mech, lambda_ppd=float(lam), cls_target=(target == "cls_row"))
        if lambda_sig is not None:
            c["lambda_sig"] = float(lambda_sig)
    if drop_masked:
        c["drop_masked"] = True
    if save_at:
        c["save_at"] = list(save_at)                  # E8 (C25): step-tagged snapshots ckpt_<step>.pt (val steps only)
    axes = dict(arm=arm, mech=mech, lambda_ppd=float(lam), lr=str(lr), policy=policy, target=target, seed=seed, steps=steps)
    if save_at:
        axes["save_at"] = list(save_at)
    if init_from:
        axes.update(init_from=init_from, freeze_encoder=bool(freeze))
        if reinit_head:
            axes["reinit_head"] = True
    return c, axes


def matches(run, axes):
    """Does an existing run's config sit on this cell? (reuse_existing is verified, never trusted.)"""
    p = ROOT / "configs" / f"{run}.yaml"
    if not p.exists():
        return False, f"{run}: no config"
    c = yaml.safe_load(p.read_text())
    want = dict(seed=axes["seed"], lr=float(axes["lr"]), steps=axes["steps"], prior_source="real")
    if axes["arm"] == "ds":
        want["policy"] = axes["policy"]
    else:
        want.update(policy_main=axes["policy"], lambda_ppd=axes["lambda_ppd"], cls_target=(axes["target"] == "cls_row"))
        if c.get("mode", "ema") != axes["mech"]:
            return False, f"{run}: mode {c.get('mode', 'ema')} != {axes['mech']}"
    want.update(init_from=axes.get("init_from") or None, freeze_encoder=bool(axes.get("freeze_encoder", False)))   # E6: a scratch run must not claim an init_from cell
    have = dict(c, init_from=c.get("init_from") or None, freeze_encoder=bool(c.get("freeze_encoder", False)))
    bad = {k: (have.get(k), v) for k, v in want.items() if have.get(k) != v}
    return (not bad), (f"{run}: {bad}" if bad else "")


def e1_best(argv, key="best_cell", flag="--e1-best"):
    for i, a in enumerate(argv):
        if a == flag:
            kv = dict(x.split("=") for x in argv[i + 1].split(","))
            return dict(lam=float(kv["lam"]), lr=kv["lr"], source=flag)
    if E1_ARTIFACT.exists():
        b = json.loads(E1_ARTIFACT.read_text()).get(key)
        if b:
            return dict(lam=float(b["lambda_ppd"]), lr=str(b["lr"]), source=f"{E1_ARTIFACT.relative_to(ROOT)}[{key}]")
    return None


def plan(spec, best, best_lat=None):
    """experiment id -> list of (config | None for a reused run, axes, run_name)."""
    ex = {e["id"]: e for e in spec["experiments"]}
    out = {}
    a = ex["E1"]["axes"]
    out["E1"] = [cell("dual", m, l, lr, a["policy"], a["target"], s)
                 for m in a["mechanism"] for l in a["lambda_ppd"] for lr in a["lr"] for s in a["seeds"]]
    a = ex["E1b"]["axes"]
    out["E1b"] = [cell("dual", m, l, lr, a["policy"], a["target"], s, lambda_sig=ls)
                  for m in a["mechanism"] for ls in a["lambda_sig"] for l in a["lambda_ppd"] for lr in a["lr"] for s in a["seeds"]]
    a = ex["E3"]["axes"]
    out["E3"] = [cell(arm, "none", 0.0, lr, a["policy"], "bar32", s) for arm in a["arm"] for lr in a["lr"] for s in a["seeds"]]
    if best:
        a = ex["E2"]["axes"]
        out["E2"] = [cell("dual", "ema", best["lam"], best["lr"], p, t, s) for t in a["target"] for p in a["policy"] for s in a["seeds"]]
        a = ex["E5"]["axes"]
        out["E5"] = [cell("dual", "ema", best["lam"], best["lr"], "mixed", "cls_row", 0, steps=st, extra=f"{st // 1000}k") for st in a["steps"]] + \
                    [cell("ds", "none", 0.0, best["lr"], "any_cell", "bar32", 0, steps=st, extra=f"{st // 1000}k") for st in a["steps"]]
        if re.search(r"drop_masked", (ROOT / "model/pfn.py").read_text()):      # C8 landed
            a = ex["E4"]["axes"]
            out["E4"] = [cell("dual", "ema", best["lam"], best["lr"], "mixed", "cls_row", s, drop_masked=True) for s in a["seeds"]]
    if best_lat and "E6" in ex:
        # E6 (C15): the pure-lat cell's EMA encoder (one run per seed) -> ds head. Stage 2 always lr 5e-4 / any_cell / bar32.
        a = ex["E6"]["axes"]; lr = a["lr"][0]; seeds = a["seeds"]
        lat = {s: name("dual", "ema", best_lat["lam"], best_lat["lr"], "mixed", "cls_row", s) for s in seeds}
        out["E6"] = ([cell("ds", "latfrozen", 0.0, lr, "any_cell", "bar32", s, steps=5000, extra="5k", init_from=lat[s], freeze=True) for s in seeds]
                     + [cell("ds", "latinit", 0.0, lr, "any_cell", "bar32", s, steps=5000, extra="5k", init_from=lat[s]) for s in seeds]
                     + [cell("ds", "none", 0.0, lr, "any_cell", "bar32", s, steps=5000, extra="5k") for s in seeds]
                     + [cell("ds", "latinit", 0.0, lr, "any_cell", "bar32", s, steps=STEPS, extra="20k", init_from=lat[s]) for s in seeds]
                     + [cell("ds", "none", 0.0, lr, "any_cell", "bar32", s) for s in seeds])          # scratch 20k = reused real_ds
    if best_lat and "E7" in ex:
        # E7 (C23): both arms to convergence - same steps, same optimizer (schedule-free), lat init vs scratch, one run per seed each.
        a = ex["E7"]["axes"]; lr = a["lr"][0]; seeds = a["seeds"]
        lat = {s: name("dual", "ema", best_lat["lam"], best_lat["lr"], "mixed", "cls_row", s) for s in seeds}
        out["E7"] = [c for T in a["steps"] for s in seeds for c in
                     (cell("ds", "latinit", 0.0, lr, "any_cell", "bar32", s, steps=T, extra=f"{T // 1000}k", init_from=lat[s]),
                      cell("ds", "none", 0.0, lr, "any_cell", "bar32", s, steps=T, extra=f"{T // 1000}k"))]
    if best_lat and "E8" in ex:
        # E8 (C25): one pure-lat run per seed to `pretrain_steps` with snapshots, then a 5k ds fine-tune from every snapshot
        # (init_from = the snapshot file; mech token lat<step> carries the pretraining budget in the run name).
        a = ex["E8"]["axes"]; seeds = a["seeds"]; T = a["pretrain_steps"]; snaps = a["snapshots"]; lr = a["lr"][0]; F = a["finetune_steps"]
        pt = {s: cell("dual", "ema", best_lat["lam"], best_lat["lr"], "mixed", "cls_row", s, steps=T, extra=f"{T // 1000}k", save_at=snaps) for s in seeds}
        out["E8"] = [pt[s] for s in seeds] + [cell("ds", f"lat{k}", 0.0, lr, "any_cell", "bar32", s, steps=F, extra=f"{F // 1000}k",
                                                   init_from=f"runs/{pt[s][0]['run_name']}/ckpt_{k}.pt") for s in seeds for k in snaps]
    if "E10" in ex:
        # E10 (C27): data-space pretraining with the latent cell's masking (policy mixed), snapshots -> head-reinit 5k fine-tune.
        a = ex["E10"]["axes"]; seeds = a["seeds"]; T = a["pretrain_steps"]; snaps = a["snapshots"]; lr = a["lr"][0]; F = a["finetune_steps"]
        pt = {s: cell("ds", "dspre", 0.0, lr, "mixed", "bar32", s, steps=T, extra=f"{T // 1000}k", save_at=snaps) for s in seeds}
        out["E10"] = [pt[s] for s in seeds] + [cell("ds", f"dsinit{k}", 0.0, lr, a["finetune_policy"], "bar32", s, steps=F, extra=f"{F // 1000}k",
                                                    init_from=f"runs/{pt[s][0]['run_name']}/ckpt_{k}.pt", reinit_head=bool(a.get("reinit_head"))) for s in seeds for k in snaps]
    return out


def main():
    spec = yaml.safe_load(SPEC.read_text())
    ex = {e["id"]: e for e in spec["experiments"]}
    best = e1_best(sys.argv[1:])
    best_lat = e1_best(sys.argv[1:], key="best_cell_lat", flag="--e1-best-lat")
    out_dir = ROOT / "configs"
    manifest = {"source": str(SPEC.relative_to(ROOT)), "e1_best": best, "e1_best_lat": best_lat, "experiments": {}}
    n_written = 0
    earlier = {}                     # run name -> experiment that already owns it (E2's (cls_row, mixed) cell IS E1's best cell)
    for eid, cells in plan(spec, best, best_lat).items():
        e = ex[eid]
        reuse = list(e.get("reuse_existing", []))
        # a reused run must sit on exactly one still-unclaimed cell of this grid
        claimed, runs = {}, {}
        for run in reuse:
            hit = [ax for _, ax in cells if matches(run, ax)[0] and json.dumps(ax, sort_keys=True) not in claimed]
            if not hit:
                raise SystemExit(f"{eid}: reuse_existing run {run} matches no free cell: " +
                                 "; ".join(matches(run, ax)[1] for _, ax in cells if matches(run, ax)[1])[:400])
            claimed[json.dumps(hit[0], sort_keys=True)] = run
        n_dup = 0
        for c, ax in cells:
            key = json.dumps(ax, sort_keys=True)
            if key in claimed:
                runs[claimed[key]] = dict(ax, reused=True)
            elif c["run_name"] in earlier:                       # same cell already trained by an earlier experiment
                runs[c["run_name"]] = dict(ax, reused=True, reused_from=earlier[c["run_name"]])
                n_dup += 1
            else:
                (out_dir / f"{c['run_name']}.yaml").write_text(HEADER + yaml.safe_dump(c, sort_keys=False))
                runs[c["run_name"]] = dict(ax, reused=False)
                n_written += 1
        gen = sum(not r["reused"] for r in runs.values())
        assert len(runs) == e["runs"] and gen == e["runs"] - len(reuse) - n_dup, (eid, len(runs), e["runs"], gen, len(reuse), n_dup)
        manifest["experiments"][eid] = dict(runs=runs, n_runs=len(runs), n_generated=gen, n_reused=len(reuse) + n_dup,
                                            n_reused_from_other=n_dup, artifact=e["artifact"], ledger=e["ledger"], test=e["test"], verdict=e["verdict"])
        earlier.update({run: eid for run in runs})
        print(f"{eid}: {len(runs)} runs = {gen} generated + {len(reuse)} reused" + (f" + {n_dup} shared with an earlier experiment" if n_dup else ""))
    for eid in ("E2", "E4", "E5", "E6", "E7", "E8"):
        if eid not in manifest["experiments"]:
            print(f"{eid}: pending (needs E1 " + ("best_cell_lat" if eid in ("E6", "E7", "E8") else "best") + (" + C8" if eid == "E4" else "") + ")")
    MANIFEST.write_text(json.dumps(manifest, indent=1) + "\n")
    print(f"wrote {n_written} configs + {MANIFEST.relative_to(ROOT)}")
    # generated configs that no experiment claims any more (e.g. E2 / E5 from an earlier best_cell): listed, deleted only with --prune
    live = {run for e in manifest["experiments"].values() for run in e["runs"]}
    stale = sorted(p for p in out_dir.glob("v4_*.yaml") if p.stem not in live)
    for p in stale:
        if "--prune" in sys.argv:
            p.unlink()
        print(("pruned " if "--prune" in sys.argv else "STALE (not in manifest; --prune to delete) ") + str(p.relative_to(ROOT)))


if __name__ == "__main__":
    main()
